package com.example.gerrymanderdemo.model.Enum;

public enum PreferenceType {
    //TODO: Check All Weights Name
    STATE_NAME, COMMUNITY_OF_INTEREST, MAJMIN_UP, MAJMIN_LOW, NUM_BATCH_RUN,
    POLITICAL_FAIRNESS, POPULATION_EQUALITY,
    EFFICIENCY_GAP, PARTISAN_FAIRNESS, ETHNIC_MINORITY_DATA,
    GRAPH_THEORETICAL_COMPACTNESS, ETHNIC_MINORITY, GRAPH_THEORETICAL, NUM_DISTRICTS
}