package com.example.gerrymanderdemo.model.Enum;

public enum PreferenceType {
    //TODO: Check All Weights Name

// COMMUNITY_OF_INTEREST  GRAPH_THEORETICAL_COMPACTNESS
    NUM_BATCH_RUN, NUM_DISTRICTS, STATE_NAME, COMMUNITY_OF_INTEREST,
    NUM_MMDISTRICTS, COMPACTNESS, LENGTH_WIDTH, COMPETITIVENESS, MAJMIN_UP, MAJMIN_LOW,
    EFFICIENCY_GAP,
    POPULATION_EQUALITY,
}