package com.example.gerrymanderdemo.model.Enum;

public enum PreferenceType {
    //TODO: Check All Weights Name
    POLITICAL_FAIRNESS, POPULATION_EQUALITY, STATE_NAME, COMMUNITY_OF_INTEREST,
    EFFICIENCY_GAP, PARTISAN_FAIRNESS, ETHNIC_MINORITY_DATA,
    ETHNIC_MINORITY, GRAPH_THEORETICAL, NUM_DISTRICTS, MAJMIN_UP, MAJMIN_LOW
}

// COMMUNITY_OF_INTEREST  GRAPH_THEORETICAL_COMPACTNESS