package com.example.gerrymanderdemo.model.Enum;

public enum WeightType {
    COMPACTNESS, POLITICAL_FAIRNESS, POPULATION_EQUALITY, COMMUNITY_OF_INTERNESTS,
    EFFICIENCY_GAP, PARTISIAN_FIRNESS, ETHNIC_MINORITY_DATA, GRAPH_THEORETICAL_COMPACTNESS
}
