package com.example.gerrymanderdemo.model.Enum;

public enum WeightType {
    //TODO: Check All Weights Name
    COMPACTNESS, POLITICAL_FAIRNESS, POPULATION_EQUALITY, COMMUNITY_OF_INTERNEST,
    EFFICIENCY_GAP, PARTISIAN_FIRNESS, ETHNIC_MINORITY_DATA, GRAPH_THEORETICAL_COMPACTNESS,
    ETHNIC_MINORITY, GRAPH_THEORETICAL
}
